### ISSUE TITLE
catch up with xenon v2.6.2

### ISSUE THREAD

**Issue by marksantcroos** [xenon-middleware/pyxenon#37]
Would it be possible update pyxenon to the latest xenon?

**Comment by jhidding** [comment]
pyxenon depends on xenon-grpc, which is currently built against xenon 2.6.0, I have upgraded master branch to use xenon-grpc 2.3.0.

**Comment by jhidding** [comment]
Do you need some feature from xenon 2.6.2 that is not in 2.6.0? In that case I will ask my colleague (@sverhoeven) to create a new build.

**Comment by marksantcroos** [comment]
Hi Jan, not anything specific, but didn't fancy running into issues that were already fixed.

**Comment by marksantcroos** [comment]
Btw, I didn't realize that the __version__ didn't refer to the xenon version, but to the xenon-grpc version. Would it make sense to align those?

**Comment by jhidding** [comment]
Yes I agree, it would make sense, but could also introduce problems with semantic versioning. At some point we decided to decouple minor versions between Xenon and Xenon GRPC. Specifically, Xenon GRPC has a slightly different API due to limitations between the purely OOP Xenon architecture and the message based GRPC interface.

**Comment by marksantcroos** [comment]
Fair enough.
Could the underlying versions also be exposed, or is it already the case?
That would suffice for me too.

**Comment by jhidding** [comment]
Yes, the version string for Xenon is in `xenon.version.xenon_version`, I could make it more findable

**Comment by marksantcroos** [comment]
Ah, perfect! This is more than enough for me as it is now.
